version: '3'

services:
  db:
    build: PostgreSQL
    environment:
      POSTGRES_PASSWORD: example
    restart: always
    ports: 
      - 5435:5432
    command:
      - -c
      - max_prepared_transactions=100
  pgadmin:
    # use server "db", login "postgres" pwd "example"
    image: dpage/pgadmin4:4.28
    ports: 
      - 8086:80
    environment: 
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret          

